config/routes.rb
Eyebleach::Application.routes.draw do

  root 'homes#index'
  get 'gallery/' => 'homes#gallery'
  get 'mockup/' => 'homes#mockup'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
#stupid scaffold_controller pluralization....
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
  end
  def gallery
    imageCount = 0
    pageCount = 0
    #@gifs = ["http://i.imgur.com/AUFDta8.gif", "http://i.imgur.com/u1t7FgH.gif", "http://i.imgur.com/m3i1P.gif", "http://i.imgur.com/VANDhe7.gif", "http://i.imgur.com/0z7pboO.gif", "http://i.imgur.com/NPQJBbp.gif"]
    @gifs = []

    while imageCount < 6
      reddit = open("http://www.reddit.com/r/Eyebleach/.json?limit=100&count=#{pageCount * 25}") { |f| f.read } 
      puts "#{pageCount * 25}"
      data = JSON.parse(reddit)
      data["data"]["children"].each do |datum|
        if /.gif/.match(datum["data"]["url"]) && datum["data"]["thumbnail"] != "nsfw"
          gif = datum["data"]["url"]
          @gifs << gif
          #do processing here
          `wget #{gif}  -P /home/lee/src/eyebleach/test_images/`
          puts "GIFFF!!!!! #{gif}"
          filename = File.basename("#{gif}")
          basename = File.basename("#{gif}", ".gif")
          `convert /home/lee/src/eyebleach/test_images/#{filename} /home/lee/src/eyebleach/test_images/#{basename}-frame%01d.gif`
          imageCount = imageCount + 1
        end
      end
      pageCount = pageCount + 1
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render action: 'show', status: :created, location: @home }
      else
        format.html { render action: 'new' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params[:home]
    end
end

app/controllers/tv_controller.rb
class TvController < WebsocketRails::BaseController
  include ActionView::Helpers::SanitizeHelper

  def initialize_session
    puts "Session init!"

  end

  def create_channel_list
    @channels = {}
    Dir.foreach('/home/lee/src/eyebleach/test_images/') do |filename|
      if filename !~ /[a-z0-9]*frame\d*.gif/i #no frames!!!
        if filename != "." && filename != ".." #no directories!
        @channels[File.basename("/home/lee/src/eyebleach/test_images/#{filename}", '.gif')] = 0
        end
      end
    end
    #lets make our lists
  end

  def do_frame_lookup
    @channels.each_key do |channel|
      #re = Regexp.new("#{channel}\d")
      totalFrames = -1
      Dir.foreach('/home/lee/src/eyebleach/test_images/') do |filename|
        if filename.match(/#{channel}-frame\d*/) != nil
          totalFrames += 1
        end
      end
      @channels[channel] = totalFrames
    end
  end
          


  def frame_message(ev, msg, frame_no, total_frames, channel_name)
    broadcast_message ev, { 
      msg_body: msg,
      frame_no: frame_no,
      total_frames: total_frames,
      channel_name: channel_name
    }
  end

  def channel_list(ev, channels)
    broadcast_message ev, {
      channels: channels
    }
  end

  #needs to take frame num as param
  def next_frame
    #populate our @channels instance vaiable
    create_channel_list
    do_frame_lookup

    if File.exist?("/home/lee/src/eyebleach/test_images/#{message[:channel_name]}-frame#{message[:frame_no]}.gif")
      image = Base64.encode64(File.open("/home/lee/src/eyebleach/test_images/#{message[:channel_name]}-frame#{message[:frame_no]}.gif").read)
      frame_message :next_frame, image, message[:frame_no], @channels[message[:channel_name]], message[:channel_name]
    else
      image = Base64.encode64(File.open("/home/lee/src/eyebleach/test_images/#{message[:channel_name]}-frame0.gif").read)
      frame_message :next_frame, image, 0, @channels[message[:channel_name]], message[:channel_name]
    end
  end

  def get_channels
    create_channel_list
    chan_list = []
    @channels.each_key do |channel|
      chan_list << channel
    end
    channel_list :channel_list, chan_list
  end

  def change_channel
    puts 'changing channel'
    #need to store current channel in connection data
    
  end

  def client_disconnected
    puts "goodbye"
  end

  def client_connected
    puts "client #{client_id} connected"
    #lets make our lists

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/gallery.html.erb
<div id="container">
    <% @gifs.each do |gif| %>
      <div class="item"><img src="<%= gif %>"/></div>
    <% end %>
</div>

app/views/homes/index.html.erb
<div class="tv">
  <div class="tvBorder">
    <div id="screen">
      <div id="tv" data-uri="<%= request.host %>:<%= request.port %>/websocket"></div>
    </div>
    <div class="controls">
      <a id="next_channel" class="channel" href="#" title="Next Channel">&#x1f63f;</a>
      <a id="previous_channel" class="channel" href="#" title="Previous Channel">&#x1F63B;</a>
    </div>
  </div>
</div>

app/views/homes/mockup.html.erb
<h1>Mockup!</h1>
<div class="tv">
  <div class="tvBorder">
    <div id="screen">
      <div>
      <img src="http://robohash.org/foo.jpg?size=480x360" class="frame"/>
      <div>


    </div>
    <div class="controls">
      <a id="next_channel" class="channel" href="#" title="Next Channel">&#x1f63f;</a>
      <a id="previous_channel" class="channel" href="#" title="Previous Channel">&#x1F63B;</a>
    </div>
  </div>

</div>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eyebleach</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>